# Generated by Django 4.1 on 2022-09-05 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='path',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='menu',
            old_name='title',
            new_name='url',
        ),
    ]
