# Generated by Django 4.1 on 2022-09-02 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookInfo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=20, verbose_name='名称')),
                ('create_date', models.DateField(verbose_name='发布日期')),
                ('read_num', models.IntegerField(default=0, verbose_name='阅读量')),
                ('discuss_num', models.IntegerField(default=0, verbose_name='评论量')),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章',
                'db_table': 'bk_tool',
            },
        ),
    ]
